### ISSUE TITLE
If I add a template with slot='table-row-after', there is a missing th

### ISSUE THREAD

**Issue by ianhd** [xaksis/vue-good-table#136]
How do I specify a column for my custom template column?

Example: 

```
    <vue-good-table :columns="columns"
                    :rows="rows">
        <template slot="table-row-after" scope="props">
            <td>{{ props.row.myField }}</td>
        </template>
    </vue-good-table>
```

If I specify 2 columns in my `columns` attribute, then have that third column defined via template, then there ends up being just 2 `th`'s in the `<thead>`. How do I specify a third column, one where I can do something like `{label: 'myField'}` (I can't b/c `field` is required, which I don't need b/c I'm defining it myself). Screenshot below. Thanks!

https://i.imgur.com/DcoiV7U.png

**Comment by arivera12** [comment]
I am not really sure if your issue is certainly referenced with my issue  but
 
There is an issue with `<td>` and `<th>` elements when using slots. 

Take a look of my link [138](https://github.com/xaksis/vue-good-table/issues/138)

I am trying to look what is wrong with `<td>` that aren't being rendered on IE11.

All versions of IE aren't not working as expected.

**Comment by xaksis** [comment]
@ianhd you'll need to specify the header for the third column as well. Field in this case is optional (I will update the document to reflect this). the template is only for the row data. so your columns should look something like: 
```javascript
columns: [
 {
    label: 'columnA',
    field: 'fieldA',
},
{
    label: 'columnA',
    field: 'fieldA',
},
{
    label: 'Dynamic Column',
},
]
```
closing this. Let me know if this doesn't work for you and I'll re-open.
