### ISSUE TITLE
width property dont make any changes to table width

### ISSUE THREAD

**Issue by Tooblippe** [xaksis/vue-good-table#155]
when the width is set via the width : '100px' setting the table does not adjust...

could bootrap be respoinsible?

**Comment by xaksis** [comment]
hey @Tooblippe as this jsfiddle shows, this is working fine: 
https://jsfiddle.net/aks9800/80dj8vug/

it could very well be that your custom styles are effecting the width, or the table content itself could be responsible for it. Since this isn't a library specific question, I'll close this for now.
