### ISSUE TITLE
Non hard coded filter options

### ISSUE THREAD

**Issue by StefanOosten** [xaksis/vue-good-table#206]
Let's say you get an array from the database with all possible filter options.

Is it possible to use this in the dropdown filterOptions, instead of hard coded values?

**Comment by xaksis** [comment]
hey @StefanOosten, yes, that should work just fine. filterOptions is just a javascript object as long as it's in the right format it'll do what it's supposed to. 

load data from your server and store it in this.myData. then do filterOptions="myData"

**Comment by StefanOosten** [comment]
Hey @xaksis thanks for the reply.

I still can't get it to work? Check out this jsfiddle:

https://jsfiddle.net/obfky53g/10/

**Comment by xaksis** [comment]
@StefanOosten you're trying to set data from another data member, this won't work since the data is not initialized till after the data function returns. If I add: 
```javascript
mounted() {
  	this.columns[0].filterOptions = this.myData;
  }
```
to your fiddle, it works as expected. 

refer to this StackOverflow question: 
https://stackoverflow.com/questions/46491468/how-to-put-a-value-of-data-object-in-another-data-object-vuejs
