### ISSUE TITLE
Duplicate keys detected: 'rows-dropdown-option-20'

### ISSUE THREAD

**Issue by Sharvadze** [xaksis/vue-good-table#207]
Hi, thanks for the nice component! I'm getting this warning and it's kinda annoying. Any idea how to fix it?

![image](https://user-images.githubusercontent.com/964784/37489968-96f21ad8-2899-11e8-8ea5-20c536873406.png)

**Comment by xaksis** [comment]
hey @Sharvadze, thanks for using the component. As the warning suggests, it's happening because drop-down options for rowsPerPage has duplicates in them. Looks like you're using the customRowsPerPage and have duplicates in them?

going to close for now, if this isn't the case lets create a jsfiddle to reproduce this and I'll re-open the ticket to investigate.

**Comment by Sharvadze** [comment]
@xaksis Thanks for guidance. Actually I have added :customRowsPerPageDropdown="[20]" and warning has gone away. Thanks again
