### ISSUE TITLE
How to add custom buttons for action in a row?

### ISSUE THREAD

**Issue by sudhir600** [xaksis/vue-good-table#323]
Hi Team,
Is there any way to add custom button in row and bind any action.
See this screenshot- 
![image](https://user-images.githubusercontent.com/4952560/42085720-df21730e-7bae-11e8-9c4e-3b7be7b39e94.png)

I tried below code but its rendering html code as a string. 
```
rows: [
	   { id:1, 'action': '<input type="button" value="hello">' },
      ],
```

and above code is rendring like this.
![image](https://user-images.githubusercontent.com/4952560/42085892-47c1468c-7baf-11e8-9dcc-273777ea6a11.png)

**Comment by xaksis** [comment]
@sudhir600 as the documentation states, there are two ways you can do this. 
1. add property `html: true` to your column (however if you're adding buttons etc this won't suffice since you probably need some interaction. So use method 2. 

2. Custom row template - https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template

closing.
