### ISSUE TITLE
question about package.json of that project

### ISSUE THREAD

**Issue by iliran11** [xaksis/vue-good-table#34]
The `main` property in `package.json` points to `src/index.js` and not to `/dist/vue-good-table.min.js` 

is it a mistake?
and if not - why is it so?

**Comment by xaksis** [comment]
@iliran11 hey! that is not a mistake.... `/dist/vue-good-table.min.js` is meant to be used as a standalone (in case you want to use it on codepen or jsfiddle). For regular vue projects, the plugin to include is `src/index.js` so that your local build etc can be debugged properly and your build process can take care of minification etc for prod.

closing. please re-open if you have further questions/concerns.
