### ISSUE TITLE
Show all rows causes total page number is minus rows number (ex. 1 from -28)

### ISSUE THREAD

**Issue by wussup** [xaksis/vue-good-table#342]
### Issue Type
Bug

### Specs
vue-good-table 2.11.0
Chrome 67.0.3396.99

### Expected Behavior
When I select show all rows, I would like to see info on right bottom : page 1 from 1.

### Actual Behavior
I actually see page 1 from -28 (rows number)

### Steps to Reproduce the Problem
1. Load page with table
2. Select show all records
3. See pages section

### Possible solution
Change method in Table.vue from

```
 pageChangedEvent() {
       return {
         currentPage: this.currentPage,
         currentPerPage: this.currentPerPage,
         total: Math.floor(this.totalRowCount / this.currentPerPage)
       };
     }
```

to

```
 pageChangedEvent() {
       return {
         currentPage: this.currentPage,
         currentPerPage: this.currentPerPage,
         total: this.currentPerPage === -1 ? 1 : Math.floor(this.totalRowCount / this.currentPerPage)
       };
     }
```

**Comment by wussup** [comment]
@xaksis no problem ;) could you please tell me, when it can be done?

**Comment by xaksis** [comment]
@wussup v2.11.1 now has the fix. Unfortunately, it wasn't as simple as correcting the pageChangeEvent object... since that is just the payload to the outside component for a page change event specifically (which isn't fired on perPageChange). 

Internally VgtPagination had to be updated to convey the right currentPage value to VgtPaginationPageInfo component so that the input widget could be adjusted accordingly. 

closing.
