### ISSUE TITLE
[Fixed Header] Header not scroll with horizontal scrollbar

### ISSUE THREAD

**Issue by kn7007** [xaksis/vue-good-table#381]
### Issue Type (delete the irrelevant ones) 

- [x] Bug

### Specs
What version are you using?
2.12.2
What browser?
Chrome
### Expected Behavior
What did you expect to happen?
Header should be scroll with table body when scroll
### Actual Behavior
What actually happened?
Header not scroll with horizontal scrollbar on table body
### Steps to Reproduce the Problem
Just use `fixed-header` configuration on table with 6 column.

### Demo
https://codepen.io/cspx99/pen/pONXoO
![capture](https://user-images.githubusercontent.com/35058512/44890226-a6d0a980-ad03-11e8-8840-37f9217fbb18.JPG)

**Comment by kn7007** [comment]
Hi @xaksis! for a long time to investigate, i found a solution for fixed header issue. This is my example: https://jsfiddle.net/kn7007/3xb57qp2/17/. Please consider refactor and integrate it to your lib.

Thank you!

**Comment by xaksis** [comment]
@kn7007 thank you for the suggestion!! But looking at it... I don't think we can force a no-wrap on td, because data could be really long and people would want it to wrap in the cell. If I remove the no-wrap... it creates an issue - try expanding the table. Good attempt though, I'll look into this in more detail shortly.
