### ISSUE TITLE
Go Flexbox

### ISSUE THREAD

**Issue by the94air** [xaksis/vue-good-table#415]
### Issue Type
- [x] Enhancement Request
### Specs
**What version are you using?**
v2.14.1

**What browser?**
Chrome v68
### Expected Behavior
**What did you expect to happen?**
All the styling is based on CSS floats and not modern flexbox.
### Actual Behavior
**What actually happened?**
All styles should be changed to flexbox for all features like filters, global search, and pagination... etc. I would love to create a PR but I won't be soon enough though. Other than that, I will make a PR. How does that sound? Will flexbox be a good idea in your perspective of 'vue-good-table'?
Thanks.

**Comment by xaksis** [comment]
Hey @the94air I don't think moving to flexbox is  as of now because of following reasons: 
1. Quite a few clients of vue-good-table are on IE 9 and flex is not supported there. In fact, even IE 11 implementation of flex is full of bugs
1. There's no real gain in switching from float to flex specifically for vue-good-table. In fact, there's loss in cross-browser compatibility
1. vue-good-table's styles are imported separately from the component, so If you really want to use flex, you can replace the vgt styles with your own. I'd encourage you to create your flex theme and contribute to the library!

Closing.
