### ISSUE TITLE
[ASK] error button on table

### ISSUE THREAD

**Issue by balinux** [xaksis/vue-good-table#454]
### Issue Type (delete the irrelevant ones) 

- [ ] Bug
- [ ] Enhancement Request
- [x] Question

### Specs
using  "vue-good-table": "2.15.3",

using chorome

### Expected Behavior
my button can't trigger editPost Function

![image](https://user-images.githubusercontent.com/10473273/47899781-98df0680-deb5-11e8-962e-de1fc05947f7.png)

and this is capture from chrome devtools
![image](https://user-images.githubusercontent.com/10473273/47899906-fd9a6100-deb5-11e8-8780-2aba260f03cd.png)

**Comment by owensource** [comment]
What error if any are you receiving in console when you attempt to click?

To me, this looks like it might be related to the scoping of 'this' inside the template string of your push method.

Potential solutions include converting your main/callback functions to traditional functions (instead of anonymous arrow functions) and/or explicitly binding 'this' and/or adding 'this' to your @click method inside of the template string.

`var vm = this`
`@click=this.editPost`

**Comment by xaksis** [comment]
@balinux looks like you're using strings to render html. In this case all associated triggers/events are stripped before the html is rendered. If you want to use triggers and events in your generated html, you'll need to do it via custom row templates: 
https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template

closing.
