### ISSUE TITLE
New image column type

### ISSUE THREAD

**Issue by roberto910907** [xaksis/vue-good-table#482]
### Issue Type (delete the irrelevant ones) 

-  Bug
- [x] Enhancement Request
-  Question

### Specs
What version are you using?
2.16.0

What browser?
Chrome Version 71.0.3578.98 (Build oficial) (64 bits)

I've been looking for a nice/easy way to show images inside a column. I think this is a very common use case when building tables. Reading [this answer](https://github.com/xaksis/vue-good-table/issues/309) I was able to make it work but just wondering if it would be possible to create a new [type](https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#type) option called **image** so the content of the [field](https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#field) will be wrapped inside an **img** html tag. And in the same way that we have extra options for the **date** type, we could add **imageWidth** and **imageHeight** to this new type.

How does that sound to you?

**Comment by xaksis** [comment]
hey @roberto910907 thank you for the suggestion. At the moment I'm leaning against it only because it's fairly simple to use column type html and put an image in there '<img src="" class="" />'. 

the reason date was added into the type, is because date comparison/sorting etc are different compared to numbers or text. With images comparison/sorting etc don't come into play.

thanks. Closing.
