### ISSUE TITLE
SearchTrigger with delay

### ISSUE THREAD

**Issue by juehai** [xaksis/vue-good-table#483]
### Issue Type (delete the irrelevant ones) 

- [x] Enhancement Request

### Specs
What version are you using?
2.16.0

What browser?
Chrome

### Expected Behavior
What did you expect to happen?

Add v-debounce="delay" supported on searchTerm input box. 
When doing searching, the onChange happened almost real time, it's working fine when only do a local searching, but it will cause a lot of requests to the server side, and if we use an async method to request the server, the typing order may be changed, the final query string will be overridden by some unfinished string.

E.g.: 
* Synchronized searching for "Alex"
- request 1: A
- request 2: Al
- request 3: Ale
- request 4: Alex

* Async search for "Alex"
- request 1: A
- request 2: Alex
- request 3: Al
- request 4: Ale

Therefore the last searching result will be searched for 'Ale' which is a wrong answer.

I know there is an option for configuring search trigger as 'enter', but it would be good if support delayed search.

**Comment by ow-en** [comment]
A couple of things: first, if you are having issues with the search term querying on keyup, I would recommend adding a trigger, 'enter', for instance.

Second, you aren't far off with your server-side table, but you're missing an item.

To enable functional pagination, you need not only totalRecords, but also perPage and relevantRecords. A lot of this, though, depends on what you're using on the back end. The server needs to return a count of all of the records (totalRecords), but only a count (you don't want all of the records being returned at once). To keep track of which page you're on, your server needs to keep track of the number of records per page (perPage), and return a set of records based on the total less the count of the current page.

In short, the server should only be returning sets of X records per query.  If pagination isn't working, it's because your server-side logic isn't correctly tracking the current page. The server should be performing a skip/take operation. Skip up to X page, take Y # of records, currentPage = X*Y/perPage.

Without tracking all of those variables, the server will either return all records at once, or won't be able to paginate once a single set is returned. I would recommend reviewing your pagination logic on the server-side.

Where relevantRecords comes in is after a filter, sort, search, or other modifier is applied. After performing your pagination logic, you would perform your server-side sort, filter, etc logic. The # of records returned after all modifiers have been applied is relevantRecords.

relevantRecords then supercedes totalRecords as the total count tracker. Pagination is then performed on relevantRecords instead of totalRecords.

Hopefully that helps you out. Server side tables are difficult to implement. It has taken me weeks to successfully implement 5 server-side tables in production with multi-column filter, multi-column sort, and global search/status filter/crud actions dropdowns, but they work wonderfully.

The issue with remote mode/server-side tables isn't this plugin. This plugin is more or less just a UI when you need to convert a table to server-side. Because everyone's server-side logic/language/framework/etc is going to be different, there is absolutely no way @xaksis could possibly implement that functionality in the plugin, it would be an absolutely massive amount of work to do it for even one language. The best thing I can recommend is to take a look at older examples of table pagination/filter/sort logic for your particular stack, and work off of that.

**Comment by juehai** [comment]
@kaphert thanks, I will try later once I finish the current project.

**Comment by juehai** [comment]
@ow-en appreciate your help.

I believe the server-side table is not too hard unless you don't know how do you do searching.

My code shows clearly I passed the totalRecords and the result dataset which is the this.rows. 

This plugin supposes to show the server-side dataset in the current page, and use the totalRecords to make the pagination.

My problem was when I returned 5 rows data and totalRecords was 100, the table rendered 5 rows but the pagination still showing 5 rows and 1 page in total. 

I'm now sure why you thought the issue was the remote/server-side as I don't know what else the server-side can do at the moment, except returning a dataset and totalNumbers. But thanks anyway.

**Comment by ow-en** [comment]
@juehai if what you described is actually the case, then the totalRecords property that you have set in your data object is either not reactive, or isn't being updated by the server correctly.

The only thing the plugin does (from what I've seen) when in remote mode regarding pagination is to 1.) update total pages by using totalRecords / perPage, and 2.) emit an on-page-change event that triggers loadItems after incrementing/decrementing the reactive 'page' prop in data.

If totalRecords is indeed being returned by the server as 100, and the plugin is still not paginating, that would indicate to me that the property isn't binding correctly.

When you say you're not sure why I thought the issue would be server-side, well, that's because in remote mode the server performs almost every operation. All of the pagination, sorting, filtering, and searching that would normally be performed in the client has to be constructed manually from scratch on the server, specific to whatever stack the end-user is working with. 

Having gone through this process in an enterprise application multiple times now, and successfully getting 5 remote mode tables to work with multi-column filter, sort, and search- I was speaking from my experience. When going through this process, virtually every issue that I encountered was server-logic-related. Creating all of that logic on the server manually is a lot more involved than it can seem. Even the pagination logic was far more involved than I initially envisioned it would be. Anyway, that's where I was coming from with my initial comment.

Once again, I would double-check that your totalRecords property is binding correctly. I would use the Vue devtools and throw a breakpoint in right before your data comes in from the server. See if the totalRecords prop updates correctly. If it does indeed bind to the vue instance, and the plugin still doesn't update the total pages, I'm not sure what the issue would be.

Also, how did you implement your pagination logic on the server? Are you performing some sort of skip/take operation? I'm just curious.

Best of luck,

**Comment by xaksis** [comment]
Hi @juehai 
> My problem was when I returned 5 rows data and totalRecords was 100, the table rendered 5 rows but the pagination still showing 5 rows and 1 page in total.

sounds like it's the classic using camel-case instead of kebab-case for component issue. try using total-rows instead of totalRows on your component. 

from the documentation: https://vuejs.org/v2/guide/components-props.html

closing.
