### ISSUE TITLE
Not able to search with .  in table with search options

### ISSUE THREAD

**Issue by sumancholleti** [xaksis/vue-good-table#510]
Not able to search with .  in table with search options

### Specs
What version are you using?
2.2.16.0
What browser?
any
### Expected Behavior
What did you expect to happen?
Able to search with . if the row present with 3.34
### Actual Behavior
What actually happened?

### Steps to Reproduce the Problem
Please detail your steps here

1.
1.
1.

### jsfiddle
If you provide a jsfiddle reproducing the issue, it'll be addressed much faster.
you can use [this as base](https://jsfiddle.net/aks9800/57a2a4ce/)

**Comment by ow-en** [comment]
@sumancholleti 

Can you be a little bit more specific as to what the issue is? Are you attempting to search/filter a floating point integer (i.e: 10.75024)?

If so, two things come to mind: you may need to check the type prop on your column, or you may want to look into a format or filter function, referenced in the [documentation](https://xaksis.github.io/vue-good-table/guide/configuration/column-options.html#formatfn).

I'm happy to help out, but please provide some more context, and/or reproduce the issue in a fiddle (if possible), per the issue template.

**Comment by sumancholleti** [comment]
In this fiddle https://jsfiddle.net/aks9800/57a2a4ce/ i tried to search for 3.34 , nothing comes even though last column has values like 3.34

**Comment by xaksis** [comment]
v2.16.3 should fix this.
