### ISSUE TITLE
Save scrollbar position

### ISSUE THREAD

**Issue by cannap** [xaksis/vue-good-table#542]
hi,
FIRST awesome work thank you so much

### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
Latest

is there a way to save the current scroll position when i use max-height?
the problem is use the click event to switch the page but it also  reloads the table each time.

maybe a event when someone scrolls to get the current Y axis position?

i got it working to save the current sortoption
```js

   mounted () {
      this.localSort = JSON.parse(localStorage.getItem('lastMarketSort'))
    },

methods..
   onSortChange (params) {
        localStorage.setItem('lastMarketSort', JSON.stringify(params[0]))
      }
``` 

and use it like

```html
  :sort-options="{
      enabled: true,
      initialSortBy: localSort
    }"
```

thanks

**Comment by xaksis** [comment]
hey @cannap! So, currently, the table doesn't emit scroll position. After reading your post, this actually seems to be an implementation change that you can make on your end. Why does the table reload each time you switch page if it's the same data that user needs to go back to (including scroll position)? Maybe instead of destroying the table, just use `v-show` property so it's just hidden from view.

Either way, I think this use-case can be handled outside of the table plugin itself. closing.
