### ISSUE TITLE
Make a selected Option responsive?

### ISSUE THREAD

**Issue by ChadTaljaardt** [xaksis/vue-good-table#57]
Hello, 

Im making the options in my table selectable, in which a user can select a single row and it will be added to a array of "Selected Options".

I followed the answer from here: https://github.com/xaksis/vue-good-table/issues/43

When i check the checkbox, it calls the method in which i can console.log the results and it works. Is it possible to make it so that when a option is selected it will be added to a array and when its deselected it will be removed?

Thanks a lot.

**Comment by xaksis** [comment]
@ChadTaljaardt this doesn't seem to be related to vue-good-table. The way i'd do it is - 
1. make sure every row has a unique id
2. when you click on a row, call a function
3. if the id of the clicked row matches one of the rows in your *selected array* remove it, else add the clicked row to the selected row. 

closing this, since it is not related to vue-good-table. Please re-open if you have more questions or concerns.
