### ISSUE TITLE
No rows found hides the table, does not display empty state correctly

### ISSUE THREAD

**Issue by paulhuisman** [xaksis/vue-good-table#600]
**Issue Type**
> Question

**Specs**
What version are you using?
2.18.0

What browser?
Chrome

**Description**
What should be the empty value of `rows` for the empty state of the table to display correctly? If i set `rows` to an empty array it does not render the table at all. I'd like to display the empty state if there's no rows found.

**Comment by xaksis** [comment]
hey @paulhuisman,
when rows is an empty array, the table should not be gone. here's an example: 
https://jsfiddle.net/aks9800/ou1cLpy8/

sounds like there's either a v-if in your code or there's an error preventing the table from rendering. Can you reproduce this in a jsfiddle?

**Comment by paulhuisman** [comment]
Thanks for your swift response @xaksis 

Yes, i'm using a v-if because i'm retrieving the data via awaits, so it only renders once the data is retrieved.

Code:

```<MoleculeDataTable
      v-if="orders && ordersCount"
      :ordersCount="ordersCount"
      :orders="orders"
      :columns="columns"
    />```

**Comment by xaksis** [comment]
Yeah so that'd explain it... you're only rendering that component if there are orders... so this isn't really a table thing, more of how the component is being rendered. you should just let it render and have `rows = []` while it waits for the response. 

If you don't want to show the default message: you can override it by using the empty-slot:
https://xaksis.github.io/vue-good-table/guide/configuration/#empty-state-slot
change it to 'loading data...' or something. and then once your api returns, change the message to 'no data for table' if there are no orders.

closing.

**Comment by paulhuisman** [comment]
Thanks:)
