### ISSUE TITLE
Unable to limit check boxes to one item

### ISSUE THREAD

**Issue by joshk132** [xaksis/vue-good-table#602]
### Issue Type (delete the irrelevant ones) 

- [x] Question

### Specs
What version are you using?
Latest as of September 9th 2019

What browser?
Chrome

### Expected Behavior
What did you expect to happen?
I would like to be able to only select one row/item not all

### Actual Behavior
What actually happened?
Currently, I am able to select all items which causes issues with my back end logic

### Steps to Reproduce the Problem
Please detail your steps here

1. I click on the checkbox column and I am able to select multiple and even all with a single click. Would like to be able to limit the selection to only one row/item

Settings:
:selectOptions="{
	enabled: true,
	selectOnCheckboxOnly: true,
	selectionInfoClass: 'alert alert-info m-b-0 no-rounded-corner',
	selectionText: 'rows selected',
	clearSelectionText: 'clear',
}

**Comment by xaksis** [comment]
hey @joshk132, if you only want people to select one row, why not use row-click event as opposed to a checkbox table?

**Comment by joshk132** [comment]
@xaksis I had considerd that but the reason I had decided a checkbox would be better was it gave the option to have multiple 'quick buttons' to different actions like edit, delete, view

**Comment by xaksis** [comment]
got it, I still think per row action is better for this since you'll never allow users to select more than one row. Just create a custom actions column at the end and have view, edit, delete per row. If you are concerned about space, you can add a dropdown in the custom column instead. Here's an example from one of my projects: 
![image](https://user-images.githubusercontent.com/4627120/64574052-e16c1980-d33b-11e9-970b-104c5687e648.png)

**Comment by xaksis** [comment]
closing.
