### ISSUE TITLE
Support for dynamic slot names (e.g. custom row template)

### ISSUE THREAD

**Issue by fegbers** [xaksis/vue-good-table#668]
### Issue Type
- [x] Enhancement Request

As in the [custom row template](https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template) shown, you have to look on the field and add the custom functionality. If the field is the "default", you have to reimplement the default every time. Perhaps you have a bit more complex default template (e.g. if formattedRow.length > X, show only the first 50 chars and add dots). Therefore you always have to add the logic.
If we use [dynamic slot names](https://vuejs.org/v2/guide/components-slots.html#Dynamic-Slot-Names), it could simplify the structure. The only issue is that this feature is only supported in vue above of 2.6.0.

Currently i only have this issue for the custom row template. Perhaps there are also some improvements on other slots.

Any opinitions?

**Comment by xaksis** [comment]
@fegbers thank you for your question. I'm actually unsure how named slots would help in this case? could you come up with a code example to clarify? How would you supply slot-A vs slot-B without checking for your logic condition?

**Comment by fegbers** [comment]
@xaksis I will provie a code example the next days.

**Comment by fegbers** [comment]
@xaksis  Just created a draft pull request (#669).
Of course, some methods are superfluous and maybe not ideal.
Does it clearify my intention?
Perhaps there are also some more slots to improve.. But i adapted only the row and the header.

**Comment by fegbers** [comment]
Just for information

Some other issues that could be solved with some more slots:
#616
#632
#655

**Comment by davidjr82** [comment]
@fegbers @xaksis 

Could we use this idea to use filter columns as slots? Recently, the multiselect filter has been merged. Although this is really nice, it has downsides too:

- Users only can use this multiselect component, and not other one if they would want to.
- Package has more kb, even a user doesn't want to use it.

Imagine a user now wants to have a date filter, and submit a PR with it. Other wants a range date filter. More PRs.

If we can use a slot to provide the filter each user wants, we can keep the package slim, and let the users to use the filter they want, and provide an example in docs for a "default filter" if they want to use a standard filter.

What do you think, does it make sense?

Thanks!

**Comment by xaksis** [comment]
@fegbers, I'm going to take a look at the PR this weekend and see if I understand your intent. 

@davidjr82 these are valid concerns, please create a separate ticket for this and assign to @TheJaredWilcurt as they have more clarity on that update.

**Comment by xaksis** [comment]
@fegbers here are my concerns with your approach: 

- fields are not always strings, they could be functions in which case the slots would fail.
- fields are also not required. You could have custom columns added to your table which don't refer to any property on the row. (Action columns)
- I also don't see how this'd work for something where you want to provide a custom template based on a condition: Like, if (rowValue > 100) color it red. What slot name would you provide?
- Sometimes row values are HTML entities. What would happen to row slot names then?

Regarding the other tickets mentioned: 
https://github.com/xaksis/vue-good-table/issues/616 - The problem here is not the ability to provide slots, but the interface between slot and filter functionality will need some thinking. how does it work with external filter values? initial filter values, etc. But yes, certainly can be done via slots.

https://github.com/xaksis/vue-good-table/issues/632 - this can be solved via slots, yes. Just haven't had time and it doesn't seem to be a show stopper for anyone.

https://github.com/xaksis/vue-good-table/issues/655 - same as 616.

**Comment by fegbers** [comment]
@xaksis Okay, I didn't think about things like that.
In order to avoid the problems you mentioned, there should be some kind of clear identification. Maybe the class? I dont know..
If there are no other ideas, you can close this problem and the relevant PR.
