### ISSUE TITLE
Custom theme implementation

### ISSUE THREAD

**Issue by fullstackdev-online** [xaksis/vue-good-table#688]
### Issue Type

- [x] Question

### Specs
What version are you using?
2.19.1

What browser?
Chrome

### Expected Behavior
Based on comments from #572 I try to use a custom theme, I expect scoped style should change default theme colors.

### Actual Behavior
What actually happened?
Default theme colors are always shown.

### Steps to Reproduce the Problem

1. in mycomponent.vue I create table and define theme:

>
    <template>
        ...
        <vue-good-table
          ...
          style-class="vgt-table condensed bordered"
          theme="my-theme"
        />
        ...
    </template
>

2. then in the styles part of this file define colors overrides:

>    
    <style lang="scss">
        .vgt-table.mytheme {
          $thead-bg-color-1: rgb(0, 0, 0) !default;
          $thead-bg-color-2: rgb(0, 0, 0) !default;
          $chevron-color: lighten($thead-bg-color-1, 10%);
          $text-color: rgb(255, 255, 255) !default;
          $secondary-text-color: #8290A7 !default;
          $border-color: #435169;
          $border-color-td: $border-color;
          $input-border-color: $border-color;
          $table-bg: #324057;
          $highlight-color: #445168;
        }
     </style>
>

3. the page has default theme (white colors)

### Code
[codepen with example](https://codepen.io/fullstackdev-online/pen/rNVZVoO)

**Comment by TheJaredWilcurt** [comment]
That won't work, you need to import the source Sass files. and apply the variable changes prior to the import.

```scss
$thead-bg-color-1: rgb(0, 0, 0) !default;
$thead-bg-color-2: rgb(0, 0, 0) !default;
$chevron-color: lighten($thead-bg-color-1, 10%);
$text-color: rgb(255, 255, 255) !default;
$secondary-text-color: #8290A7 !default;
$border-color: #435169;
$border-color-td: $border-color;
$input-border-color: $border-color;
$table-bg: #324057;
$highlight-color: #445168;

@import "../node_modules/vue-good-table/src/styles/style.scss";
```

**Comment by fullstackdev-online** [comment]
> That won't work, you need to import the source Sass files. and apply the variable changes prior to the import.
> 
> ```css-scss
....
> @import "../node_modules/vue-good-table/src/styles/style.scss";
> ```

Thank you! It helped.

**Comment by p0psicles** [comment]
@TheJaredWilcurt  I seems you know more of this styling stuff.
I'm convertiing my css files for my project to scss.
The reason for this is, is that I was hoping to have more control on how many times I write my vue-good-table stylings.

Right now in each component that I use vgt, I have css ruls like:
```css
/** Use this as table styling for all table layouts */
.vgt-table-styling >>> .vgt-table {
    width: 100%;
    margin-right: auto;
    margin-left: auto;
    text-align: left;
    border-spacing: 0;
}
```

I tried moving everything to one css file name vgt-tables.css. And import it.
Like:
```html
<style>
@import `../style/vgt-tables.css`;
</style>
```

But that doesn't seem to work.
This does work though:
```html
<style src='../style/vgt-tables.css`>
</style>
```
But then you cant place any other css in the style tags.

I also tried importing them as global imports using webpack sass-loader option, additionalData. But effectively that's the same.

Your solution provided here: https://github.com/xaksis/vue-good-table/issues/688#issuecomment-627421263
Only works when you want to override sass variables right? So that isn't usuable for other styling?

I'm just looking at a DRY solution for reusing vgt styling. Any help is welcome.
