### ISSUE TITLE
Can't expand collapsed record at 2nd page

### ISSUE THREAD

**Issue by amane-ro** [xaksis/vue-good-table#692]
### Issue Type (delete the irrelevant ones) 

- [x] Bug?

### Specs
What version are you using?
2.19.1

What browser?
Chrome 80.0.3987.149

### Expected Behavior
If a group record, a grouped table spans pages, the next page can also be expanded from collapsed.

### Actual Behavior
Can be expanded only on the first page for each record.

### Steps to Reproduce the Problem
Please detail your steps here

1. Enable groupOptions.
1. Set data to exceed 'perPage'.
1. Try expanding the collapsed row on page two.

### jsfiddle
https://jsfiddle.net/m5zo97fb/2/

**Comment by severinrohner** [comment]
I faced a very similar issue, perhaps it has the same reason.

The collapse feature is broken if you filter a table.
There is an index problem:
1. Search in a table, that the first row [1] is filtered out
2. Click to the new top row [2] => nothing happen
3. Click to the second row [3] => the top row [2] collapse

IMHO should be used 'vgt_header_id' instead of index in this function call:
https://github.com/xaksis/vue-good-table/blob/ed7c365a5aac68e4391c97cf80c4428bb7574046/src/components/Table.vue#L153

The vgt_header_id should then match with the array index from filteredRows
https://github.com/xaksis/vue-good-table/blob/ed7c365a5aac68e4391c97cf80c4428bb7574046/src/components/Table.vue#L893

**Comment by xaksis** [comment]
definitely a bug. Will release a fix shortly. @severinrohner thank you so much for digging into it. You're absolutely correct - index is not a unique identifier for rows.

**Comment by xaksis** [comment]
v2.19.2 should fix this. Thanks again for pointing this out @amane-ro @severinrohner

**Comment by severinrohner** [comment]
@xaksis Thank you very much for the fix and the new release. You are doing a very good job!
