### ISSUE TITLE
External Search in HTML columns

### ISSUE THREAD

**Issue by contriveitup** [xaksis/vue-good-table#698]
### Issue Type 

- [x] Question

### Specs
What version are you using?
**2.19.1**

What browser?
**Chrome 80.0.3987.163** 

### Expected Behavior
External search to filter data in columns with **Html: true**

### Actual Behavior
It searches only for text fields and the text inside any HTML tag does not gets filter via external search.

### Steps to Reproduce the Problem
Attached v-model to an input box with `<input  v-model="searchTerm"  />`

In Vue Component add the following settings:

```
<vue-good-table
        :columns="columns"
        :rows="rows"
        :pagination-options="pagination"
        :search-options="{enabled: true,externalQuery: searchTerm}"
      >
```

This works for the columns/rows which has plain text value but does not filter the table results for some text wrapped in lets say an anchor tag<a> or div's

Is there a workaround for this?

Thanks!

PS: Awesome work. One of the best Vue plugins i have used.

**Comment by xaksis** [comment]
hey @contriveitup, filtering text out of HTML for the filter would not be in the scope for native filtering functionality because HTML structure could be complex. For your use-case, it'd make more sense to use a row template where you can provide a field value that would then be searchable. 
https://xaksis.github.io/vue-good-table/guide/advanced/#custom-row-template

Closing.
