### ISSUE TITLE
Vue router and Remote table

### ISSUE THREAD

**Issue by andrew-svirin** [xaksis/vue-good-table#798]
When loading table by url `?page=2&perPage=20&searchTerm=iiii&sort=0%255Btype%255D%3Dasc%260%255Bfield%255D%3Dpaid_at`
it making remote request for data with specified conditions.
But I can not find how to setup initial pagination, sorting, searching values. Values are always default.
Is it possible to setup default values from route on the table and which way it to do to not make  remote request multiple times?

**Comment by andrew-svirin** [comment]
I doing some strange things, but they a causing multiple requests.
Like these
```
this.sortOptions = Object.assign({}, this.sortOptions, {
  initialSortBy: this.serverParams.sort,
});
this.paginationOptions = Object.assign({}, this.paginationOptions, {
   setCurrentPage: this.serverParams.page,
   perPage: this.serverParams.perPage,
 });
this.$refs['payments-table'].globalSearchTerm = this.serverParams.searchTerm;
```
It is more similar with some hack.

**Comment by xaksis** [comment]
hey @andrew-svirin one way to prevent multiple requests is put a `v-if` on the table and only show the table once you've setup the option objects with your url queries on page load.

You can read the documentation about how to set up initial values: https://xaksis.github.io/vue-good-table/guide/configuration/pagination-options.html

Either way, this is more a use-case specific implementation rather than a problem with the plugin.

closing.

**Comment by andrew-svirin** [comment]
Thank you @xaksis
Any way to make it from options? `this.$refs['payments-table'].globalSearchTerm = this.serverParams.searchTerm;`
