### ISSUE TITLE
Hybrid remote mode

### ISSUE THREAD

**Issue by carmolim** [xaksis/vue-good-table#892]
### Issue Type
- [x] Question

### Specs
What version are you using?
"vue-good-table": "^2.21.10",

### Question
Is possible to use the remote mode in a hybrid way?
I want the sorting to happen on the back-end and the pagination on both, let me clarify: I want to fetch the first 500 rows and make pagination for these 500 rows on the front-end but at the last page, or the one before that, I want to fetch the next 500 rows.

Is possible to do something like that? And what would be the best way to accomplish that?

Thanks!

**Comment by xaksis** [comment]
Unfortunately no, this isn't possible. If you really want to do something like this, you'd need to build your own logic on top of the regular mode. Just give it 500 rows. You'd also need to provide a custom pagination widget because the default widget will show a max of 500 rows which won't be true in your case. So can be done but will be significant work on top of the regular (non-remote) table.

**Comment by carmolim** [comment]
Thank you for the reply!
